line_length:
  warning: 130
  error: 300
  ignores_comments: true
  ignores_function_declarations: true

type_body_length:
  warning: 300

type_name:
  max_length: 60

file_length:
  warning: 500
  ignore_comment_only_lines: true

identifier_name:
  min_length:
    warning: 2
  excluded:
    - id    
    - ad
    - vc
    - vm
    - translatesAutoresizingMaskIntoConstraints

nesting:
  type_level: 2

shorthand_operator: warning

force_try: warning

function_body_length:
  warning: 50

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

large_tuple:
  warning: 3

disabled_rules:
  - class_delegate_protocol # linter can't tell when restricted to AnyObject subclass

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - fatal_error_message
  - first_where
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - operator_usage_whitespace
  - override_in_extension
  - private_action
  - private_outlet
  - prohibited_super_call
  - protocol_property_accessors_order
  - sorted_first_last
  - sorted_imports
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

warning_threshold: 10
